services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5


  airflow-init:
    image: apache/airflow:2.10.5
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"   
      GOOGLE_CLOUD_PROJECT: fourth-truck-506708-s5

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ${APPDATA}/gcloud:/home/airflow/.config/gcloud:ro

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "


  airflow-webserver:
    image: apache/airflow:2.10.5

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      GOOGLE_CLOUD_PROJECT: fourth-truck-506708-s5
      AIRFLOW__WEBSERVER__WORKERS: 2
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 300

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ${APPDATA}/gcloud:/home/airflow/.config/gcloud:ro

    command: webserver


  airflow-scheduler:
    image: apache/airflow:2.10.5

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      GOOGLE_CLOUD_PROJECT: fourth-truck-506708-s5

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ${APPDATA}/gcloud:/home/airflow/.config/gcloud:ro

    command: scheduler


volumes:

  postgres-db-volume: